//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreativeSystemDesktop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.OrderProducts = new HashSet<OrderProduct>();
        }
    
        public string ProductArticleNumber { get; set; }
        public string ProductName { get; set; }
        public string ProductDescription { get; set; }
        public string ProductCategory { get; set; }
        public string ProductPhoto { get; set; }
        public string ProductManufacturer { get; set; }
        public decimal ProductCost { get; set; }
        public Nullable<byte> ProductDiscountAmount { get; set; }
        public int ProductQuantityInStock { get; set; }
        public string Unit { get; set; }
        public Nullable<int> MaxDiscount { get; set; }
        public string Provider { get; set; }
        public string imagePath
        {
            get
            {
                if(ProductPhoto == null || ProductPhoto.Trim() == "")
                {
                    return $"{AppDomain.CurrentDomain.BaseDirectory}Images/picture.png";
                }
                else
                    return $"{AppDomain.CurrentDomain.BaseDirectory}Images/{ProductPhoto}";
            }
        }
        public string haveStock
        {
            get
            {
                if (ProductQuantityInStock == 0)
                    return "Нет на складе";
                else
                    return "Есть на складе" ;
            }
        }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderProduct> OrderProducts { get; set; }
    }
}
